version:                      '3.7'

services:
    bot_reposter:
        build:                .
        command:              python -B -OO -m src && echo $RETURN 
        environment:
            # LOGGING_LEVEL: INFO
            PYTHONUNBUFFERED: 1
            DATA: |
                {
                    "email": null,
                    "username": "remors.b13",
                    "password": "ciuccio99",
                    "phone": null,
                    "proxy": null,
                    
                    "geotags": ["nice"],
                    "hashtags": ["casino", "money", "lamborghini"],
                    "competitors": ["instagram", "kimkardashian"],
                    "inspirations": ["archillect.png"],
                    "captions": ["hey guys, fresh new photos here", "bella rega"],
                    "comments": ["awesome", "nice", "bella"],
                    "media_posted": [],
                    "messages": ["ciao"]
                }
          
            RETURN: "{}"

