version: '3.7'

services:
    bot:
        build: .
        environment:
            - DATA_FILE_PATH=/data/data.json
            - CACHE_FILE_PATH=/data/cache.db
            - COOKIE_FILE_PATH=/data/cookie.json
            - PYTHONUNBUFFERED=1
        volumes:
            - data/:/data
