version:                      '3.7'

services:
    bot_reposter:
        build:                .
        command:              python -B -OO -m src result.json && echo `cat result.json` 
        environment:
            # LOGGING_LEVEL: INFO
            PYTHONUNBUFFERED: 1
            DATA: |
                {
                    "email": null,
                    "username": "remors.b13",
                    "password": "ciuccio99",
                    "phone": null,
                    "proxy": null,
                    
                    "geotags": ["nice"],
                    "hashtags": ["casino", "money", "lamborghini"],
                    "competitors": ["instagram", "kimkardashian"],
                    "inspirations": ["archillect.png"],
                    "captions": ["hey guys, fresh new photos here", "bella rega"],
                    "comments": ["awesome", "nice", "bella"],
                    "media_posted": [],
                    "messages": ["ciao"]
                }
            SCRIPT: |
                    name:                            routine
                    version:                         1

                    bot:
                            username:                remors.redhence
                            password:                {{ password }}
                            latitude: 53.2734
                            langitude: -7.77832031
                            
                    filter:
                            user:
                                followers:           x > 50 and x < 1000
                                following:           x < 500
                            media:
                                likers:              x < 1000
                                hastags:             not x in ["sex", "porn", "child"]

                    delay:
                        unfollow:                    20
                        comment: 25
                        like: 20
                        follow: 20

                    actions:
                        -
                            name:                    competitors fans interactions
                            from:               user
                            nodes:
                                - {{ random.choice(competitors) }}
                            edges:
                                - feed:
                                    amount:          10
                                - shuffle:
                                    max:             1
                                    batch:           10
                                - likers:
                                    amount:          20
                                - follow
                                - feed:
                                    amount:          1
                                - like
                        -
                            name:                    geotag interactions
                            from:               geotag
                            nodes:
                                - {{ random.choice(geotags) }}
                            edges:
                                - feed:
                                    amount:          1
                                - likers:
                                    amount:          20
                                - feed:
                                    amount:          2
                                - like
                                - comment:
                                    comments:
                                        - {{ comments }}


                        -
                            name:                    repost a photo from inspirations
                            from:               user
                            nodes:
                                - {{ random.choice(inspirations) }}
                            edges:
                                - feed:
                                    amount:          10
                                - shuffle:
                                    max:             1
                                    batch:           10
                                - scrape:
                                    key:             reposted_images
                                    model:
                                        url:         x.images[0]
                                - upload_post:
                                    max:             1
                                    caption:         {{ random.choice(captions) }}
                                    geotag: monaco


