version:                      '3.7'

services:
    bot_reposter:
        build:                .
        command:              sh -c "python -B -OO -m src /result.json && echo `cat /result.json`"
        environment:
            # LOGGING_LEVEL: INFO
            PYTHONUNBUFFERED: 1
            DATA: |
                {
                    "email": null,
                    "username": "remors.redhence",
                    "password": "ciuccio99",
                    "phone": null,
                    "proxy": null,
                    "settings": {
                        "uuid": "d783237c-53d0-11e9-9665-d46e0e1b2c0d",
                        "device_id": "android-d783246c53d011e9",
                        "ad_id": "624c37e5-9766-238f-26f6-08737416aeeb",
                        "session_id": "d78324bc-53d0-11e9-9665-d46e0e1b2c0d",
                        "created_ts": 1554049205
                    },
                    "settings_path": "settings.json",
                    "geotags": ["nice"],
                    "hashtags": ["casino", "money", "lamborghini"],
                    "competitors": ["instagram", "kimkardashian"],
                    "inspirations": ["archillect.png"],
                    "captions": ["hey guys, fresh new photos here", "bella rega"],
                    "comments": ["awesome", "nice", "bella"],
                    "media_posted": [],
                    "messages": ["ciao"]
                }
            SCRIPT: |
                    name:                    routine
                    version:                 1

                    bot:
                           username:         {{ username }}
                           password:         {{ password }}
                           latitude:         53.2734
                           longitude:        -7.77832031
                           settings_path:    {{ settings_path }}

                    delay:
                       unfollow:             20
                       comment:              25
                       like:                 30
                       follow:               20

                    actions:
                       -
                           name:             unfollow
                           from:             user
                           nodes:
                                  - {{ username }}
                           edges:
                               - followers:
                                   amount:   100
                               - shuffle:
                                   max:      1
                                   batch:    100
                               - unfollow
