version: 2
jobs:
    test:
        docker:
            - image: xmorse/instagram-botnet
        environment: 
          DATA: |
                {
                    "email": null,
                    "phone": null,
                    "proxy": null,
                    "geotags": ["nice"],
                    "hashtags": ["casino", "money", "lamborghini"],
                    "competitors": ["instagram", "kimkardashian"],
                    "inspirations": ["archillect.png"],
                    "captions": ["hey guys, fresh new photos here", "bella rega"],
                    "comments": ["awesome", "nice", "bella"],
                    "media_posted": [],
                    "messages": ["ciao"]
                }
          SCRIPT: |
                bot:
                    username: {{ username }}
                    password: {{ password }}
                actions:
                    -
                         name: notify me
                         from: user
                         nodes:
                              - xmorse_
                         edges:
                              - message:
                                   messages:
                                        - ['ciao broooo']
        steps:
            - checkout
            - run: pip install dhash
            - run: mkdir /results  && python -m src  /results/return.json
            - store_test_results:
                 path: /results
            - store_artifacts:
                 path: /results
    bump:
        docker:
            - image: xmorse/bump-version
        steps:
            - checkout
            - run: GITHUB_TOKEN=$GITHUB_TOKEN /bump
            
    deploy:
        docker:
           - image: cistuff/deploy-docker
        environment:
             IMAGE_NAME: generic-repost-routine
             REGISTRY: clusterimages.fun
        steps:
             - setup_remote_docker
             - checkout
             - run: USERNAME=$DOCKER_USERNAME PASSWORD=$DOCKER_PASSWORD /deploy
             

workflows:
     version: 2
     workflow:
          jobs:
               - test
               - bump:
                    requires:
                        - test
               - deploy:
                    requires:
                        - bump 
